# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ZeddWorks
email: scott.mcleod@zeddworks.com
description: > # this means to ignore newlines until "baseurl:"
  The curation, maintenance, and mastery of software engineering
  tools and techniques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: deepresolve
github_username:  halcyon

# Build settings
markdown: kramdown

url: https://www.zeddworks.com
enforce_ssl: zeddworks.com
